---
- name: Set policy fact for run
  set_fact:
    policy_path: /etc/opt/chrome/policies
    chrome_kiosk_binary: google-chrome

# Chrome Installation
- name: Ensure Google signing key is present
  ansible.builtin.apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
- name: Ensure Google chrome repository exists
  ansible.builtin.apt_repository:
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    state: present
    filename: 'google-chrome'
    update_cache: yes
- name: Ensure Google chrome is installed
  ansible.builtin.apt:
    name: "google-chrome-{{ chrome_release_channel }}"
    state: present
    cache_valid_time: 3600

# We will create the directories but don't remove in case manually created
- name: Create chrome policy directories if needed
  ansible.builtin.file:
    path: '{{ policy_path }}/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - managed
    - recommended
  when: chrome_policies|bool or chrome_kiosk|bool or chrome_printing_disabled|bool

- name: Copy kiosk chrome launcher
  ansible.builtin.template:
    src: chrome-kiosk.sh.j2
    dest: /usr/bin/chrome-kiosk
    mode: 'a+x'
  when: chrome_kiosk|bool
