- name: Ensure Google chrome repository doesnt exists
  ansible.builtin.apt_repository:
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    state: absent
    filename: 'google-chrome'
    update_cache: yes

- name: Uninstall Chrome
  dpkg_selections:
    name: google-chrome-stable
    selection: purge

- name: Ensure Google chrome isnt installed
  ansible.builtin.apt:
    name: "google-chrome-{{ chrome_release_channel }}"
    state: absent
    purge: yes
    cache_valid_time: 3600

- name: Set policy fact for run
  set_fact:
    policy_path: /etc/chromium/policies
    chrome_kiosk_binary: chromium-browser

- name: Use PPA to avoid ubuntu using a snap package
  ansible.builtin.apt_repository:
    repo: 'ppa:phd/chromium-browser'
    update_cache: yes
  when: ansible_distribution_release != 'xenial'

- name: Pin chromium packages to PPA
  ansible.builtin.copy:
    src: phd-chromium-browser
    dest: /etc/apt/preferences.d/phd-chromium-browser
  when: ansible_distribution_release != 'xenial'

- name: Ensure chromium is installed
  ansible.builtin.apt:
    name: chromium-browser
    state: present
    cache_valid_time: 3600

    # We will create the directories but don't remove in case manually created
- name: Create chrome policy directories if needed
  ansible.builtin.file:
    path: '{{ policy_path }}/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - managed
    - recommended
  when: chrome_policies|bool or chrome_kiosk|bool or chrome_printing_disabled|bool

- name: Copy kiosk chrome launcher
  ansible.builtin.template:
    src: chrome-kiosk.sh.j2
    dest: /usr/bin/chrome-kiosk
    mode: 'a+x'
  when: chrome_kiosk|bool
