---
# Use a very basic window manager and login manager
# idesk is needed for doing a desktop icon
- name: install xorg and window managers
  ansible.builtin.apt:
    name: '{{ chrome_kiosk_wm_packages }}'
    state: present
    cache_valid_time: 3600

- name: install extra fonts
  ansible.builtin.apt:
    name: '{{ chrome_kiosk_fonts }}'
    state: present
    cache_valid_time: 3600

# We want to auto login to openbox
- name: set autologin for slim
  ansible.builtin.lineinfile:
    dest: /etc/slim.conf
    regexp: "^auto_login "
    insertafter: "^#auto_login "
    line: "auto_login yes"
- name: set default username for slim
  ansible.builtin.lineinfile:
    dest: /etc/slim.conf
    regexp: "^default_user "
    insertafter: "^#default_user "
    line: "default_user {{ ansible_user }}"
- name: remove xsession directory from slim
  ansible.builtin.lineinfile:
    dest: /etc/slim.conf
    regexp: "^sessiondir "
    line: "#sessiondir "
    backrefs: yes

# Copy over a basic menu which just lets staff reboot the machine
- name: copy openbox menu config
  ansible.builtin.copy:
    src: openbox/menu.xml
    dest: /etc/xdg/openbox/menu.xml

# Copy over a stripped down version of openbox keyboard/mouse config
# Disables multiple desktops and their shortcuts
- name: copy openbox mapping config
  ansible.builtin.copy:
    src: openbox/rc.xml
    dest: /etc/xdg/openbox/rc.xml

# Set openbox to disable screen blanking and launch chrome on boot
- name: copy openbox autostart
  ansible.builtin.copy:
    src: openbox/autostart.sh
    dest: /etc/xdg/openbox/autostart
