---
- name: Create Chrome policy files if needed
  copy:
    dest: '{{ policy_path }}/{{ item.key }}/{{ chrome_policies_filename }}'
    mode: 0644
    content: '{{ item.value|to_nice_json }}'
  when: 
    - item.value|length > 0
    - chrome_policies
  with_dict:
    managed: '{{ chrome_policies_managed }}'
    recommended: '{{ chrome_policies_recommended }}'

- name: Delete policy file if no policies are defined
  file:
    path: '{{ policy_path }}/{{ item.key }}/{{ chrome_policies_filename }}'
    state: absent
  when: item.value|length == 0
  with_dict:
    managed: '{{ chrome_policies_managed }}'
    recommended: '{{ chrome_policies_recommended }}'

- name: Delete policy files if they are no longer managed by role
  file:
    path: '{{ policy_path }}/{{ item.key }}/{{ chrome_policies_filename }}'
    state: absent
  when: not chrome_policies
  with_dict:
    managed: '{{ chrome_policies_managed }}'
    recommended: '{{ chrome_policies_recommended }}'
