- name: Set Chrome printing policies
  copy:
    dest: '{{ policy_path }}/managed/printing.json'
    mode: 0644
    content: '{{ chrome_printing_policies|to_nice_json }}'
  when: chrome_printing_disabled
  
- name: Make sure chrome printing policies are removed if not managed
  file:
    path: '{{ policy_path }}/managed/printing.json'
    state: absent
  when: not chrome_printing_disabled
